In [ ]:
import pandas as pd
import requests

In [ ]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [ ]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [ ]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,28.6827,8.715,29618
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,29.4415,8.687,22373
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,18.6925,8.570,13535
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,15.9328,8.565,17049
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,12.9814,8.553,9697

In [ ]:
df = pd.DataFrame()

In [ ]:
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)

In [ ]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,28.6827,8.715,29618
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,29.4415,8.687,22373
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,18.6925,8.570,13535
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,15.9328,8.565,17049
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,12.9814,8.553,9697
...,...,...,...,...,...,...,...
8555,8975,The Marine,A group of diamond thieves on the run kidnap t...,2006-10-13,1.8956,6.000,805
8556,266294,Sisters,Two disconnected sisters are summoned to clean...,2015-12-18,2.4102,5.968,1440
8557,14372,Leviathan,Underwater deep-sea miners encounter a Soviet ...,1989-03-17,1.8283,6.000,538
8558,11078,National Security,"Earl Montgomery, a bombastic police academy re...",2003-01-17,2.2728,5.970,1037
8559,1410,Dark Star,A group of scientists are sent on a mission to...,1974-03-30,3.9188,5.970,622

In [ ]:
df.to_csv('api.csv')