### Some Important Series Methods

In [1]:
# astype
# between
# clip
# drop_duplicates
# isnull
# dropna
# fillna
# isin
# apply
# copy

In [3]:
import numpy as np
import pandas as pd

In [12]:
subs = pd.read_csv('subs.csv')
subs.squeeze()

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [28]:
vk = pd.read_csv('/content/kohli_ipl.csv',index_col='match_no')
vk = vk.squeeze()
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [17]:
movies = pd.read_csv('/content/bollywood.csv',index_col='movie')
movies.squeeze()

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [19]:
#astype

import sys
sys.getsizeof(vk)

3472

In [24]:
sys.getsizeof(vk.astype('int16'))

2182

In [31]:
#between

vk[vk.between(50,100)].size

47

In [34]:
# clip

subs.clip(50,100)

     Subscribers gained
0                    50
1                    57
2                    50
3                    50
4                    50
..                  ...
360                 100
361                 100
362                 100
363                 100
364                 100

[365 rows x 1 columns]

In [37]:
#drop duplicates

temp = pd.Series([1,1,2,3,4,4,3,5,5,5])
temp.drop_duplicates()

0    1
2    2
3    3
4    4
7    5
dtype: int64

In [43]:
#check duplicates

temp[temp.duplicated()]

1    1
5    4
6    3
8    5
9    5
dtype: int64

In [45]:
temp.duplicated().sum()

np.int64(5)

In [46]:
vk.duplicated().sum()

np.int64(137)

In [48]:
movies.duplicated().sum()

np.int64(934)

In [38]:
temp.drop_duplicates(keep='last')

1    1
2    2
5    4
6    3
9    5
dtype: int64

In [41]:
movies.drop_duplicates()

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Sssshhh...                            Tanishaa Mukerji
Rules: Pyaar Ka Superhit Formula                Tanuja
Right Here Right Now (film)                      Ankit
Talaash: The Hunt Begins...              Rakhee Gulzar
The Pink Mirror                        Edwin Fernandes

[566 rows x 1 columns]

In [50]:
#isnull

temp = pd.Series([1,2,3,np.nan,4,np.nan])
temp[temp.isnull()]

3   NaN
5   NaN
dtype: float64

In [51]:
#count
temp.count() #count only not null values

np.int64(4)

In [54]:
#size
temp.size # total number of entries including nan

6

In [56]:
vk.isnull().sum()

np.int64(0)

In [57]:
temp.isnull().sum()

np.int64(2)

In [58]:
#dropna

temp.dropna()

0    1.0
1    2.0
2    3.0
4    4.0
dtype: float64

In [59]:
#fillna

temp.fillna(0)

0    1.0
1    2.0
2    3.0
3    0.0
4    4.0
5    0.0
dtype: float64

In [62]:
temp.fillna(temp.mean())

0    1.0
1    2.0
2    3.0
3    2.5
4    4.0
5    2.5
dtype: float64

In [64]:
#isin

vk[vk.isin([49,99])]

match_no
82    99
86    49
Name: runs, dtype: int64

In [65]:
#apply

movies

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

In [74]:
movies['lead'].apply(lambda x: x.split()[0].upper())

movie
Uri: The Surgical Strike                  VICKY
Battalion 609                             VICKY
The Accidental Prime Minister (film)     ANUPAM
Why Cheat India                          EMRAAN
Evening Shadows                            MONA
                                         ...
Hum Tumhare Hain Sanam                     SHAH
Aankhen (2002 film)                     AMITABH
Saathiya (film)                           VIVEK
Company (film)                             AJAY
Awara Paagal Deewana                     AKSHAY
Name: lead, Length: 1500, dtype: object

In [75]:
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [77]:
subs['Subscribers gained'].apply(lambda x : 'good day' if x > subs['Subscribers gained'].mean() else 'bad day')

0       bad day
1       bad day
2       bad day
3       bad day
4       bad day
         ...
360    good day
361    good day
362    good day
363    good day
364    good day
Name: Subscribers gained, Length: 365, dtype: object

In [ ]:
#copy

In [97]:
vk

match_no
1      100
2       23
3       13
4       12
5        1
      ...
211      0
212     20
213     73
214     25
215      7
Name: runs, Length: 215, dtype: int64

In [94]:
new = vk.head()
new

match_no
1     1
2    23
3    13
4    12
5     1
Name: runs, dtype: int64

In [98]:
new[1] = 100 # if you change in head or tail of the tail it will reflect in the data

In [96]:
new

match_no
1    100
2     23
3     13
4     12
5      1
Name: runs, dtype: int64

In [87]:
vk.head()

match_no
1     1
2    23
3    13
4    12
5     1
Name: runs, dtype: int64

In [99]:
new = vk.head().copy()

In [100]:
new

match_no
1    100
2     23
3     13
4     12
5      1
Name: runs, dtype: int64

In [101]:
new[1] = 200

In [102]:
new

match_no
1    200
2     23
3     13
4     12
5      1
Name: runs, dtype: int64

In [103]:
vk

match_no
1      100
2       23
3       13
4       12
5        1
      ...
211      0
212     20
213     73
214     25
215      7
Name: runs, Length: 215, dtype: int64